// Complete Demo Data
export const demoProfiles = [
  {
    id: "1",
    fullName: "John Doe",
    pic: "https://images.pexels.com/photos/4126749/pexels-photo-4126749.jpeg",
    fatherName: "Robert Doe",
    motherName: "Mary Doe",
    phone: "+91 9876543210",
    gender: "Male",
    age: "28",
    caste: "Christian",
    religion: "Hindu",
    city: "Delhi",
    employmentType: "Private Job",
    income: "500000",
    status: "Available",
    createdBy: "User",
  },
  {
    id: "2",
    fullName: "Sunil",
    pic: "https://images.pexels.com/photos/4126749/pexels-photo-4126749.jpeg",

    fatherName: "Akshay Reddy",
    motherName: "Anna Smith",
    phone: "+91 8765432109",
    gender: "Female",
    age: "25",
    caste: "Reddy",
    religion: "Christian",
    city: "Mumbai",
    employmentType: "Self Employed",
    income: "400000",
    status: "Unavailable",
    createdBy: "Admin",
  },
  {
    id: "3",
    fullName: "Alice Johnson",
    pic: "https://images.pexels.com/photos/4126749/pexels-photo-4126749.jpeg",

    fatherName: "David Johnson",
    motherName: "Linda Johnson",
    phone: "+91 7654321098",
    gender: "Female",
    age: "30",
    caste: "Christian",
    religion: "Hindu",
    city: "Bangalore",
    employmentType: "Government Job",
    income: "600000",
    status: "Available",
    createdBy: "User",
  },
  {
    id: "4",
    fullName: "Alif",
    pic: "https://images.pexels.com/photos/4126749/pexels-photo-4126749.jpeg",
    fatherName: "Suleman Khan",

    motherName: "Zulaikha",
    phone: "+91 6543210987",
    gender: "Male",
    age: "32",
    caste: "Khan",
    religion: "Muslim",
    city: "Chennai",
    employmentType: "Business",
    income: "750000",
    status: "Unavailable",
    createdBy: "Admin",
  },
];
