// Complete Demo Data
export const demoProfiles = [
  {
    id: "1",
    fullName: "John Doe",
    fatherName: "Robert Doe",
    motherName: "Mary Doe",
    phone: "+91 9876543210",
    gender: "Male",
    age: "28",
    caste: "General",
    religion: "Hindu",
    city: "Delhi",
    employmentType: "Private Job",
    income: "500000",
    status: "Available",
    createdBy: "User",
  },
  {
    id: "2",
    fullName: "Jane Smith",
    fatherName: "Michael Smith",
    motherName: "Anna Smith",
    phone: "+91 8765432109",
    gender: "Female",
    age: "25",
    caste: "OBC",
    religion: "Christian",
    city: "Mumbai",
    employmentType: "Self Employed",
    income: "400000",
    status: "Unavailable",
    createdBy: "Admin",
  },
  {
    id: "3",
    fullName: "Alice Johnson",
    fatherName: "David Johnson",
    motherName: "Linda Johnson",
    phone: "+91 7654321098",
    gender: "Female",
    age: "30",
    caste: "SC",
    religion: "Hindu",
    city: "Bangalore",
    employmentType: "Government Job",
    income: "600000",
    status: "Available",
    createdBy: "User",
  },
  {
    id: "4",
    fullName: "Bob Brown",
    fatherName: "Thomas Brown",
    motherName: "Sarah Brown",
    phone: "+91 6543210987",
    gender: "Male",
    age: "32",
    caste: "ST",
    religion: "Muslim",
    city: "Chennai",
    employmentType: "Business",
    income: "750000",
    status: "Unavailable",
    createdBy: "Admin",
  },
];
