export const listedCastes = [
  "Kamma",
  "Balija",
  "Reddy",
  "Kapu",
  "Yadava",
  "Mala",
  "Brahmin",
  "Vysya",
  "Padmasali",
  "Madiga",
  "Gowda",
  "Viswa Brahmin",
  "Intercaste",
  "Devanga",
  "Rajaka",
  "Setti Balija",
  "Vaddera",
  "Muslim",
  "Besta",
  "Gangaputra",
  "Valmiki Boya",
  "Agnikula Kshatriya",
  "Jangama",
  "Erikula",
  "Gandla",
  "Christian",
  "Iyengar",
  "Vokkaliga Gowda",
  "Lingayath",
  "Adi Karnataka",
  "Kannada Brahmin",
  "Banijiga",
  "Viswakarma",
  "Ediga",
  "Rajput",
  "Sagara Uppara",
  "Mera",
  "Naicker",
  "Scheduled Caste",
  "Jalari",
  "Kuruma",
  "Sri Vaishnava",
  "Dedukala",
  "Kurni",
  "Adi Andhra",
  "Veera Saivam",
  "Arya Vysya",
  "Beri Chettiar",
  "Saurashtra",
  "Palaekari",
  "Ayyavarlu",
  "Bhatraju",
  "Tanda (Lambadi)",
  "Thogata Veera Kshatriya",
  "Kuruhina Shetty",
  "Bhandari",
  "Swakula Sali",
  "Yogeshwar",
  "Kurubas",
  "Varma",
  "Kummari",
  "Madiwala",
  "Pallan",
  "Vaishnava Dasulu",
  "Roman Catholic",
  "Nambiar",
  "Dasari",
  "Vanjari",
  "Vada Balija",
  "Kammavar",
  "Kamma Naidu",
  "Balija Naidu",
  "Katika",
  "Relli (SC)",
  "Singh",
  "Ganga Mata",
  "Vadiyarajulu",
  "Malik",
  "Sheikh",
  "Syed",
  "Pathan",
  "Ansari",
  // "Other"
];


export const listedReligions = [
  "Hindu",
  "Muslim",
  "Christian",
  "Sikh",
  "Buddhist",
  "Jain",
  // "Other",
];
